# Generated by Django 4.0 on 2022-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0006_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
