# Generated by Django 4.0 on 2022-01-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0008_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
