# Generated by Django 4.0 on 2022-01-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0009_company_is_deleted_alter_company_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='industry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='language',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='Currency',
        ),
        migrations.AlterModelTable(
            name='education',
            table='Education',
        ),
        migrations.AlterModelTable(
            name='industry',
            table='Industry',
        ),
        migrations.AlterModelTable(
            name='job',
            table='Job',
        ),
        migrations.AlterModelTable(
            name='language',
            table='Language',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='Skill',
        ),
        migrations.AlterModelTable(
            name='state',
            table='State',
        ),
    ]
