# Generated by Django 4.0 on 2022-01-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company_info', '0012_alter_apply_table_favourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='FavouriteJob',
        ),
        migrations.AlterModelTable(
            name='favouritejob',
            table='FavouriteJob',
        ),
    ]
