# Generated by Django 4.0 on 2022-01-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0016_alter_job_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_experience',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_experience',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_project',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job_project',
            name='start_date',
            field=models.DateField(),
        ),
    ]
