# Generated by Django 4.0 on 2022-01-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company_info', '0017_alter_job_experience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Job_Category',
            },
        ),
        migrations.CreateModel(
            name='Job_Endoresements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_info.job_profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_info.skill')),
            ],
            options={
                'db_table': 'Job_Endoresements',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_info.job_category'),
        ),
    ]
