# Generated by Django 4.0 on 2022-01-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0018_job_category_job_endoresements_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_profile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
