# Generated by Django 4.0 on 2022-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0022_job_experience_user_job_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_endoresements',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
