# Generated by Django 4.0 on 2022-01-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0025_rename_blog_category_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Blog_Category',
        ),
    ]
