# Generated by Django 4.0 on 2022-01-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company_info', '0027_adminjobs_adminblogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminBlogs',
            new_name='AdminBlog',
        ),
        migrations.RenameModel(
            old_name='AdminJobs',
            new_name='AdminJob',
        ),
    ]
