# Generated by Django 4.0 on 2022-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0028_rename_adminblogs_adminblog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='creaetd_at',
            field=models.DateTimeField(default='2021-09-12'),
        ),
    ]
