# Generated by Django 4.0 on 2022-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0029_alter_blog_options_job_creaetd_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creaetd_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
