# Generated by Django 4.0 on 2022-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0031_rename_creaetd_at_job_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='country',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
