# Generated by Django 4.0 on 2022-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0032_alter_job_options_country_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='counter',
            field=models.IntegerField(),
        ),
    ]
