# Generated by Django 4.0 on 2022-01-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0033_alter_country_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('normal_post', models.BooleanField(default=False)),
                ('blog_post', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['counter']},
        ),
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company_info.post'),
        ),
    ]
