# Generated by Django 4.0 on 2022-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0034_post_alter_country_options_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='documents',
            field=models.FileField(upload_to='apply/cv'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company/logo'),
        ),
        migrations.AlterField(
            model_name='job_profile',
            name='logo',
            field=models.ImageField(upload_to='jobprofile/logo'),
        ),
    ]
