# Generated by Django 4.0 on 2022-01-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0036_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
    ]
